nicer prints in handle_error

diff --git a/util/lint/lint-022-clang-format b/util/lint/lint-022-clang-format
--- a/util/lint/lint-022-clang-format
+++ b/util/lint/lint-022-clang-format
@@ -26,9 +26,9 @@ handle_error() {
 	fi
 
 	if [ $# -ge 1 ]; then
-		echo "$1 failed,"
+		printf "%s failed, " "$1" >&2
 	else
-		echo "failure,"
+		printf "failure, " >&2
 	fi
 
 	# use `errno` tool by Lars Wirzenius found in
